### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by sivaariram** [LiamLYJ/scene_seg#2]
python train.py 
Traceback (most recent call last):
  File "train.py", line 146, in <module>
    main(args)
  File "train.py", line 34, in main
    use_same_from = args.use_same_from)
  File "/home/flash/scene_seg/data_loader.py", line 116, in __init__
    assert (len(self.folders) >= self.segmentation_regions)
AssertionError
@LiamLYJ @drogen120 @yongjie

**Comment by sivaariram** [comment]
@LiamLYJ Where to defined segmentation setting?

**Comment by LiamLYJ** [comment]
in train.py

**Comment by sivaariram** [comment]
> in train.py

--segmentation_regions 4
but still it is showing the same error

**Comment by LiamLYJ** [comment]
how many self.folders?

**Comment by sivaariram** [comment]
> how many self.folders?

Thank you @LiamLYJ  I sorted it out 
But now I getting the error with CUDA out of Memory(I will solve this on my own, also if you experienced this error before and if you have any suggestion please let me know)
